# Generated by Django 6.0.7 on 2026-08-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("themoviedb_id", models.IntegerField()),
                ("department", models.CharField(max_length=255)),
                ("job", models.CharField(max_length=255)),
                ("known_for_department", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("profile_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GuestStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("themoviedb_id", models.IntegerField()),
                ("character", models.CharField(max_length=255)),
                ("known_for_department", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("profile_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("themoviedb_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("number_of_episodes", models.IntegerField()),
                ("number_of_seasons", models.IntegerField()),
                ("origin_country", models.CharField(max_length=255)),
                ("original_language", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("poster_path", models.CharField(max_length=255)),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("themoviedb_id", models.IntegerField()),
                ("episode_count", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("poster_path", models.CharField()),
                ("season_number", models.IntegerField()),
                ("vote_average", models.FloatField()),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="api.show",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("themoviedb_id", models.IntegerField()),
                ("episode_type", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("season_number", models.IntegerField()),
                ("still_path", models.CharField(max_length=255)),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                (
                    "crew",
                    models.ManyToManyField(
                        related_name="episodes", to="api.crewmember"
                    ),
                ),
                (
                    "guests",
                    models.ManyToManyField(related_name="episodes", to="api.gueststar"),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="api.show",
                    ),
                ),
            ],
        ),
    ]
