# Generated by Django 6.0.7 on 2026-08-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crewmember",
            old_name="themoviedb_id",
            new_name="tmdb_id",
        ),
        migrations.RenameField(
            model_name="episode",
            old_name="themoviedb_id",
            new_name="tmdb_id",
        ),
        migrations.RenameField(
            model_name="gueststar",
            old_name="themoviedb_id",
            new_name="tmdb_id",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="themoviedb_id",
            new_name="tmdb_id",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="themoviedb_id",
            new_name="tmdb_id",
        ),
    ]
