# Generated by Django 6.0.7 on 2026-08-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="tmdb_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="tmdb_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="gueststar",
            name="tmdb_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="tmdb_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="show",
            name="tmdb_id",
            field=models.IntegerField(unique=True),
        ),
    ]
